# Generated by Django 3.1.2 on 2020-10-17 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('task', models.TextField(verbose_name='Описание')),
                ('status', models.CharField(choices=[('N', 'Новая'), ('P', 'Запланированная'), ('I', 'В процессе'), ('R', 'Завершенная')], max_length=50, verbose_name='Статус')),
                ('creationTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('finalTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время завершения')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
